### ISSUE TITLE
LuckPerm Meta placeholder

### ISSUE THREAD

**Issue by LurgenAU** [james090500/VelocityGUI#4]
It would be very handy to be able to use any arbitrary LuckPerms metadata value in a placeholder. Other plugins often do this through something like %luckperms_meta_prefix% to grab the "prefix" metadata item for the player.

Other suggestion placeholders include:
- current server name
- playername
- any command parameters that were passed when running the command

This last one would greatly improve the flexibility of the plugin, allowing it to be a wrapper for much more complex network-wide commands (such as LiteBans).

Great plugin, and one I'm definitely going to start using on my network. Thank you for publishing it!

**Comment by james090500** [comment]
>any command parameters that were passed when running the command

Can you expand on this @LurgenAU?

**Comment by james090500** [comment]
New placeholders added.
https://github.com/james090500/VelocityGUI/releases/tag/v1.2.2
