### ISSUE TITLE
Sudo doesn't run commands at the proxy

### ISSUE THREAD

**Issue by LurgenAU** [james090500/VelocityGUI#5]
No idea how you've achieved this, but it looks like commands are run at the game server layer. It would be helpful to have the ability for the command to be passed directly to Velocity, so Velocity plugins can't be triggered through menu entries. Maybe add a vsudo command type?

**Comment by james090500** [comment]
This is fixed with vsudo
https://github.com/james090500/VelocityGUI/releases/tag/v1.2.2
